### ISSUE TITLE
update

### ISSUE THREAD

**Issue by ionut989898** [Alph4rd/Toshinou-Ultra#32]
Salut, cand se va face update?

**Comment by Jacobsepar12** [comment]
i think today 3pm :dagger: :dancer:

**Comment by ionut989898** [comment]
ok :)

**Comment by Combidon** [comment]
it would be nice today
I see in game new x-mas boxes)

**Comment by Menawan** [comment]
will it be upgrade? or can u give a time for that, Sir:)

**Comment by DimasOzR** [comment]
how long will be updated?

**Comment by Combidon** [comment]
this is sad(

**Comment by KlaydermanN** [comment]
Всем привет! Ребят если есть рабочая версия,дайте пожалуйста!

**Comment by Combidon** [comment]
Нет рабочей версии
Разработчик морозится

**Comment by vladeez** [comment]
I hope @Alph4rd could inherit to someone his knowledges about misterious variables that he supposed to change every time the game updates. I dare to become your student if you contact me via waxcab@gmail.com so you could break free of that damn routine. Thanks you.

**Comment by Alph4rd** [comment]
Just join the discord and check the #how-to-update channel, anything missing on the tutorial just ask me there.
