### ISSUE TITLE
[Request] Change config and formation while looking for NPC (flying)

### ISSUE THREAD

**Issue by Classic1234** [Alph4rd/Toshinou-Ultra#36]
Hello, could you please add the function "Change config and formation while looking for NPC (flying)". This function would really increase amount of NPCs killed per hour,and it will increase uri per hour. Thanks in advance.

**Comment by Alph4rd** [comment]
I will work on that, shouldn't be hard

**Comment by Nebuka34** [comment]
@Alph4rd  are you gonna update the bot ?
