### ISSUE TITLE
Rip toshibot

### ISSUE THREAD

**Issue by vladhard33** [Alph4rd/Toshinou-Ultra#37]
Toshibot rip ;(

**Comment by One-Mans-Army** [comment]
Dont you think its little annoying to open an issue hour by hour?!

Give @Alph4rd a break! the bot will be updaited or not, depends on the situation and your "Issues" wont help at all.

Do not use GitHub's tracker for your own businesses!

**Comment by Alph4rd** [comment]
Thanks @One-Mans-Army
