### ISSUE TITLE
Discord link + mini tutorial? 

### ISSUE THREAD

**Issue by DeepBlue27** [Alph4rd/Toshinou-Ultra#38]
Hello,
I would like to inform you that the discord link has expired. 
I was also hoping to help this little bot to improve, could you please add a little tutorial on how to edit the swf code and where are its main functions? Thanks and sorry for bothering you

**Comment by Alph4rd** [comment]
I have updated the invite.
Also, i'm slowly writing a tutorial on the discord on how to update the bot.
