### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by Giovane01** [Alph4rd/Toshinou-Ultra#56]
new update, plz

**Comment by AvaSoller** [comment]
I can not update the line option, I will not give out to anyone and I will fix the auto-attack on the players

**Comment by Nebuka34** [comment]
is it big problem to update  line option  just update the bot we need for only palladium lol thank you

**Comment by Giovane01** [comment]
> I can not update the line option, I will not give out to anyone and I will fix the auto-attack on the players

yoy have the update?
