### ISSUE TITLE
не работает бот

### ISSUE THREAD

**Issue by den4ik4354** [Alph4rd/Toshinou-Ultra#58]
я правильно понял нет обновления не работает бот? 
в общем у меня он не работает поправки будут какие?

**Comment by FoxProjects** [comment]
@den4ik4354 да, его ещё не обновили.

**Comment by den4ik4354** [comment]
а когда примерно ждать обновления?

**Comment by FoxProjects** [comment]
@den4ik4354 ну разработчик не я. Думаю скоро появится. Он говорил что ему надо что-то исправить прежде чем он выложит обнову.
